index:
   path: /
   controller: App\Controller\HomeController::homeAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

admin-dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::indexAction

admin-users:
  path: /admin/users
  controller: App\Controller\UsersController::indexAction

admin-cards:
  path: /admin/cards
  controller: App\Controller\CardsController::indexAction

admin-decks:
  path: /admin/decks
  controller: App\Controller\DecksController::indexAction

admin-categories:
  path: /admin/categories
  controller: App\Controller\CategoriesController::indexAction

category-create:
  path: /admin/create/category
  controller : App\Controller\CategoriesController::categoryCreateAction

admin-languages:
  path: /admin/languages
  controller: App\Controller\LanguagesController::indexAction

language-create:
  path: /admin/create/language
  controller : App\Controller\LanguagesController::languageCreateAction

language-edit:
  path: /admin/edit/language/{id}
  controller : App\Controller\LanguagesController::languageEditAction

language-delete:
  path: /admin/delete/language/{id}
  controller : App\Controller\LanguagesController::languageDeleteAction