index:
   path: /
   controller: App\Controller\HomeController::homeAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

# ------------- ADMIN ---------------------

admin-dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::indexAction

admin-users:
  path: /admin/users
  controller: App\Controller\UsersController::indexAction

admin-cards:
  path: /admin/cards
  controller: App\Controller\CardsController::indexAction

admin-decks:
  path: /admin/decks
  controller: App\Controller\DecksController::indexAction

admin-categories:
  path: /admin/categories
  controller: App\Controller\CategoriesController::indexAction

admin-languages:
  path: /admin/languages
  controller: App\Controller\LanguagesController::indexAction

# ------------- USER ---------------------

deckboard:
  path: /profile/deckboard
  controller: App\Controller\DeckboardController::indexAction