# ------------- GENERAL ---------------------

index:
   path: /
   controller: App\Controller\HomeController::homeAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

contact:
  path: /contact
  controller: App\Controller\MessageController::messageCreateAction

mentions-legales:
  path: /mentionslegales
  controller: App\Controller\MentionsLegalesController::indexAction

# ------------- ADMIN ---------------------

admin-dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::indexAction

admin-users:
  path: /admin/users
  controller: App\Controller\UsersController::indexAction

admin-user:
  path: /admin/user/{id}
  controller: App\Controller\UsersController::detailAction

admin-user-delete:
  path: admin/delete/user/{id}
  controller : App\Controller\UsersController::deleteAction 

admin-cards:
  path: /admin/cards
  controller: App\Controller\CardsController::indexAction

admin-card:
  path: /admin/card/{id}
  controller: App\Controller\CardsController::detailAction

admin-card-delete:
  path: admin/delete/card/{id}
  controller : App\Controller\CardsController::deleteAction

admin-decks:
  path: /admin/decks
  controller: App\Controller\DecksController::indexAction

admin-deck:
  path: /admin/deck/{id}
  controller: App\Controller\DecksController::detailAction

admin-deck-delete:
  path: admin/delete/deck/{id}
  controller : App\Controller\DecksController::deleteAction

admin-categories:
  path: /admin/categories
  controller: App\Controller\CategoriesController::indexAction

category-create:
  path: /admin/create/category
  controller : App\Controller\CategoriesController::categoryCreateAction

category-edit:
  path: /admin/edit/category/{id}
  controller : App\Controller\CategoriesController::categoryEditAction

category-delete:
  path: /admin/delete/category/{id}
  controller : App\Controller\CategoriesController::categoryDeleteAction

category-details:
  path: /admin/category/{id}
  controller : App\Controller\CategoriesController::detailAction

admin-languages:
  path: /admin/languages
  controller: App\Controller\LanguagesController::indexAction

language-create:
  path: /admin/create/language
  controller : App\Controller\LanguagesController::languageCreateAction

language-edit:
  path: /admin/edit/language/{id}
  controller : App\Controller\LanguagesController::languageEditAction

language-delete:
  path: /admin/delete/language/{id}
  controller : App\Controller\LanguagesController::languageDeleteAction

language-details:
  path: /admin/language/{id}
  controller : App\Controller\LanguagesController::detailAction

# ------------- USER ---------------------

deckboard:
  path: /profile/deckboard
  controller: App\Controller\DeckboardController::indexAction

rechercher:
  path: /profile/rechercher
  controller: App\Controller\DecksController::rechercherVide

rechercherChaine:
  path: /profile/rechercher/{jeCherche}
  controller: App\Controller\DecksController::rechercher

rechercherDeck:
  path: /profile/rechercher/deck/{deckId}
  controller: App\Controller\DecksController::rechercherDeck

deck-fav:
  path: /profile/fav/deck/{id}
  controller: App\Controller\DecksController::deckFavAction

# ____________ cards ________________

card-gestion:
  path: /profile/cards
  controller: App\Controller\CardsController::indexCardGestionAction

card-detail:
  path: /profile/card/{id}
  controller: App\Controller\CardsController::detailCardUserAction

card-update:
  path: /profile/update/card/{cardId}/{categoryId}
  controller: App\Controller\CardsController::cardUpdateAction

card-create:
  path: /profile/create/card/{categoryId}
  controller: App\Controller\CardsController::cardCreateAction

card-delete:
  path: /profile/delete/card/{id}
  controller: App\Controller\CardsController::deleteCardUserAction

# ____________ decks ________________

deck-gestion:
  path: /profile/decks
  controller: App\Controller\DecksController::indexGestionAction

deck-detail:
  path: /profile/deck/{id}
  controller: App\Controller\DecksController::detailUserAction

deck-create:
  path: /profile/create/deck
  controller: App\Controller\DecksController::deckUserCreateAction

deck-update:
  path: /profile/update/deck/{id}
  controller: App\Controller\DecksController::deckUserUpdateAction

deck-delete:
  path: /profile/delete/deck/{id}
  controller: App\Controller\DecksController::deleteUserAction

add-card-to-deck:
  path: /profile/add-card/deck/{idCard}/{idDeck}
  controller: App\Controller\DecksController::addCardToDeckFromDeckDetailAction

remove-card-to-deck:
  path: /profile/remove-card/deck/{idCard}/{idDeck}
  controller: App\Controller\DecksController::removeCardToDeckFromDeckDetailAction

# ____________ révision & quiz ________________

revision:
  path: /profile/revision/{deckId}
  controller: App\Controller\DecksController::launchRevisionAction

quiz:
  path: /profile/quiz/{deckId}
  controller: App\Controller\DecksController::launchQuizAction
