index:
   path: /
   controller: App\Controller\HomeController::homeAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

admin-dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::indexAction
