index:
   path: /
   controller: App\Controller\HomeController::homeAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

contact:
  path: /contact
  controller: App\Controller\MessageController::messageCreateAction

mentions-legales:
  path: /mentionslegales
  controller: App\Controller\MentionsLegalesController::indexAction

# ------------- ADMIN ---------------------

admin-dashboard:
  path: /admin/dashboard
  controller: App\Controller\AdminController::indexAction

admin-users:
  path: /admin/users
  controller: App\Controller\UsersController::indexAction

admin-user:
  path: /admin/user/{id}
  controller: App\Controller\UsersController::detailAction

admin-user-delete:
  path: admin/delete/user/{id}
  controller : App\Controller\UsersController::deleteAction 

admin-cards:
  path: /admin/cards
  controller: App\Controller\CardsController::indexAction

admin-card:
  path: /admin/card/{id}
  controller: App\Controller\CardsController::detailAction

admin-card-delete:
  path: admin/delete/card/{id}
  controller : App\Controller\CardsController::deleteAction

admin-decks:
  path: /admin/decks
  controller: App\Controller\DecksController::indexAction

admin-deck:
  path: /admin/deck/{id}
  controller: App\Controller\DecksController::detailAction

admin-deck-delete:
  path: admin/delete/deck/{id}
  controller : App\Controller\DecksController::deleteAction

admin-categories:
  path: /admin/categories
  controller: App\Controller\CategoriesController::indexAction

category-create:
  path: /admin/create/category
  controller : App\Controller\CategoriesController::categoryCreateAction

category-edit:
  path: /admin/edit/category/{id}
  controller : App\Controller\CategoriesController::categoryEditAction

category-delete:
  path: /admin/delete/category/{id}
  controller : App\Controller\CategoriesController::categoryDeleteAction

admin-languages:
  path: /admin/languages
  controller: App\Controller\LanguagesController::indexAction

language-create:
  path: /admin/create/language
  controller : App\Controller\LanguagesController::languageCreateAction

language-edit:
  path: /admin/edit/language/{id}
  controller : App\Controller\LanguagesController::languageEditAction

language-delete:
  path: /admin/delete/language/{id}
  controller : App\Controller\LanguagesController::languageDeleteAction

  # ------------- USER ---------------------

deckboard:
  path: /profile/deckboard
  controller: App\Controller\DeckboardController::indexAction

card-category: #Route temporaire
  path: /profile/card/category
  controller: App\Controller\CardsController::indexChoixCategoryAction

card:
  path: /profile/create/card/{categoryId}
  controller : App\Controller\CardsController::cardCreateAction

deck:
  path: /profile/create/deck
  controller : App\Controller\DecksController::deckCreateAction